### ISSUE TITLE
plot with buffer pool usage not working, when only InnoDB is active

### ISSUE THREAD

**Issue by amitghosh-inwt** [INWT/MariaDB_Monitor#17]
The plot showing the buffer pool usage is generating an error message for our configuration:

![image](https://user-images.githubusercontent.com/4963014/75346554-3f1b0080-589f-11ea-8bc6-e14351b3eff5.png)

We are using MariaDB 10.3. There are no non-standard table engines activated.

**Comment by JanBl2411** [comment]
Bug is fixed.
